# Generated by Django 3.1.2 on 2020-11-29 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance', models.CharField(blank=True, choices=[('O', 'On hold'), ('A', 'Attended'), ('M', 'Missed')], max_length=1, null=True, verbose_name='assistance')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Día')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
