# Generated by Django 3.1.2 on 2020-11-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assistance',
            field=models.CharField(blank=True, choices=[('O', 'On hold'), ('A', 'Attended'), ('M', 'Missed')], default='O', max_length=1, null=True, verbose_name='assistance'),
        ),
    ]
