# Generated by Django 3.1.2 on 2020-11-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typePayment', models.CharField(choices=[('CC', 'Credit card'), ('DC', 'Debit card'), ('VW', 'Virtual wallet'), ('CS', 'Cash')], default='CS', max_length=2)),
                ('sellDate', models.DateField(null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='patient.patient')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
