# Generated by Django 3.1.2 on 2020-11-27 01:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UsersManager.usuario')),
            ],
            bases=('UsersManager.usuario',),
        ),
        migrations.CreateModel(
            name='ProfesionalMedico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UsersManager.usuario')),
            ],
            bases=('UsersManager.usuario',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UsersManager.usuario')),
            ],
            bases=('UsersManager.usuario',),
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UsersManager.usuario')),
            ],
            bases=('UsersManager.usuario',),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UsersManager.usuario')),
            ],
            bases=('UsersManager.usuario',),
        ),
    ]
